# This workflow will do a clean install of node dependencies, cache/restore them, build the source code
# and run tests across different versions of node
# For more information, see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build project

on:
  push:
    branches:
      - main
      - dev
      - UAT
      - release/*
      - instance/*
  pull_request:
    branches:
      - main
      - dev
      - UAT
      - release/*
      - instance/*

jobs:
  check:
    name: Build admin
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.1]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

          # install yarn
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Node.js dependencies Frontend
        run: 
          npm install

      - name: Build the project
        run: 
          npm run build
        env:
          APP_ENV: test
          NODE_OPTIONS: '--max_old_space_size=4096'